name: flutter_redux_skeleton
description: Flutter with Redux skeleton mobile application.

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.2.0
  equatable: ^1.0.1
  dio: ^3.0.7
  redux: ^4.0.0
  redux_thunk: ^0.3.0
  redux_logging: ^0.4.0
  flutter_redux: ^0.6.0
  shared_preferences: ^0.5.4+8
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
